# Generated by Django 2.0.3 on 2018-04-27 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_person_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
